### ISSUE TITLE
Typo on Java Threads Tutorial

### ISSUE THREAD

**Issue by OmerCinar811** [cs1302uga/cs1302-tutorials#5]
There is a typo in this line in the Java Threads tutorial. I couldn't see a place to submit feedback which is why I'm putting it here. The typo is put in bold.

In **offocial** Java documentation, a non-daemon thread is often referred to as a user thread; however, we chose not to use that term here since its [usual definition](https://en.wikipedia.org/wiki/Thread_(computing)#User_threads) would include both both daemon and non-daemon threads in Java. [↩](https://github.com/cs1302uga/cs1302-tutorials/blob/master/threads/brief-intro-threads.md#user-content-fnref-3-c9592371510d1f7eb13581215c8432bf)

**Comment by bjb211** [comment]
Resolved, thank you

**Comment by mepcotterell** [comment]
@OmerCinar811 Thanks!
